# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='joom_top',
    source=[
        'joom_top.cpp',
        'joom_latency_histogram.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/service_context',
    ],
)
